export const defaultOptionsAirportData = [
  {
    value: "MJU",
    label: "Tampa Padang  (MJU) - Mamuju",
    airportName: "Tampa Padang ",
    cityName: "Mamuju",
    id: "5b77a1afe7941b3b942e6597",
    airportLocation: "Mamuju, Indonesia",
    type: "airport",
    cityCode: "MJUC",
    countryName: "Indonesia",
    ref: null,
    precedence: null,
    alias: ["Kalukku", "Tampapadang", "Sulawesi Barat", "Sulbar"],
  },
  {
    value: "BXB",
    label: "Babo (BXB) - Irarutu",
    airportName: "Babo",
    cityName: "Irarutu",
    id: "5b77a1ade7941b3b942e4b44",
    airportLocation: "Irarutu, Indonesia",
    type: "airport",
    cityCode: "BXBC",
    countryName: "Indonesia",
    ref: null,
    precedence: null,
    alias: ["Papua Barat", "Bintuni", "Papua", "Teluk Bintuni", "Telukbintuni"],
  },
  {
    value: "KNO",
    label: "Kuala Namu (KNO) - Medan",
    airportName: "Kuala Namu",
    cityName: "Medan",
    id: "5b77a1aee7941b3b942e5e16",
    airportLocation: "Medan, Indonesia",
    type: "airport",
    cityCode: "MESC",
    countryName: "Indonesia",
    ref: null,
    precedence: null,
    alias: [
      "Kualanamu",
      "Deli Serdang",
      "Deliserdang",
      "MDN",
      "Sumatra Utara",
      "Sumut",
      "Danau",
      "Toba",
      "KNO",
    ],
  },
  {
    value: "PSU",
    label: "Pangsuma (PSU) - Putussibau",
    airportName: "Pangsuma",
    cityName: "Putussibau",
    id: "5b77a1b0e7941b3b942e72db",
    airportLocation: "Putussibau, Indonesia",
    type: "airport",
    cityCode: "PSUC",
    countryName: "Indonesia",
    ref: null,
    precedence: null,
    alias: [
      "Pangsuma ",
      "Putussibau ",
      " Kapuas Raya",
      "Kapuas Hulu ",
      " Danau Sentarum ",
      "Betung Kerihun",
      "Kalimantan Barat",
      "Kalbar",
    ],
  },
  {
    value: "DUM",
    label: "Pinang Kampai  (DUM) - Dumai",
    airportName: "Pinang Kampai ",
    cityName: "Dumai",
    id: "5b77a1ade7941b3b942e4eb6",
    airportLocation: "Dumai, Indonesia",
    type: "airport",
    cityCode: "DUMC",
    countryName: "Indonesia",
    ref: null,
    precedence: null,
    alias: ["Pinangkampai", "Riau", "Bukit Batrem", "Batrem"],
  },
  {
    value: "SUP",
    label: "Trunojoyo (SUP) - Sumenep",
    airportName: "Trunojoyo",
    cityName: "Sumenep",
    id: "5b77a1b0e7941b3b942e7a94",
    airportLocation: "Sumenep, Indonesia",
    type: "airport",
    cityCode: "SUPC",
    countryName: "Indonesia",
    ref: null,
    precedence: null,
    alias: [
      "Nasional Trunojoyo ",
      "Madura",
      " Pulau Madura",
      "Madura Island ",
      " Truno Joyo",
    ],
  },
  {
    value: "DPS",
    label: "Ngurah Rai (DPS) - Denpasar-Bali",
    airportName: "Ngurah Rai",
    cityName: "Denpasar-Bali",
    id: "5b77a1ade7941b3b942e4e7b",
    airportLocation: "Denpasar-Bali, Indonesia",
    type: "airport",
    cityCode: "DPSC",
    countryName: "Indonesia",
    ref: null,
    precedence: null,
    alias: [
      "Ngurahrai",
      "I Gusti Ngurah Rai",
      "Gusti Ngurah Rai",
      "I Gusti",
      "Bali",
      "Bal",
      "DPS",
    ],
  },
  {
    value: "KBU",
    label: "Kotabaru (KBU) - Kotabaru",
    airportName: "Kotabaru",
    cityName: "Kotabaru",
    id: "5b77a1aee7941b3b942e5d23",
    airportLocation: "Kotabaru, Indonesia",
    type: "airport",
    cityCode: "KBUC",
    countryName: "Indonesia",
    ref: null,
    precedence: null,
    alias: [
      "Gusti Syamsir Alam",
      "Gusti Sjamsir Alam",
      "Gusti Samsir Alam",
      "Kota baru",
      "Stagen",
      "Pulau Laut Utara",
      "Kalimantan Selatan",
      "Kalsel",
    ],
  },
  {
    value: "LSW",
    label: "Malikussaleh (LSW) - Lhok Seumawe",
    airportName: "Malikussaleh",
    cityName: "Lhok Seumawe",
    id: "5b77a1afe7941b3b942e6434",
    airportLocation: "Lhok Seumawe, Indonesia",
    type: "airport",
    cityCode: "LSWC",
    countryName: "Indonesia",
    ref: null,
    precedence: null,
    alias: [
      "Malikus Saleh",
      "Lhokseumawe",
      "Loksumawe",
      "Lok sumawe",
      "Aceh Utara",
      "North Aceh",
      "Aceh",
      "Lhoksumawe",
      "lhok sumawe",
    ],
  },
  {
    value: "MWK",
    label: "Matak (MWK) - Matak",
    airportName: "Matak",
    cityName: "Matak",
    id: "5b77a1afe7941b3b942e6ab5",
    airportLocation: "Matak, Indonesia",
    type: "airport",
    cityCode: "MWKC",
    countryName: "Indonesia",
    ref: null,
    precedence: null,
    alias: ["Pal Matak", "Anambas", "Kepri", "Kepulauan Riau", "Kep. Riau"],
  },
];
