export const defaultOptionsAirportData = [
  {
    value: 'MLG',
    label: 'Abdul Rachman Saleh (MLG) - Malang',
    airportName: 'Abdul Rachman Saleh',
    cityName: 'Malang',
    id: '5b77a1afe7941b3b942e65b9',
    airportLocation: 'Malang, Indonesia',
    type: 'airport',
    cityCode: 'MLGC',
    countryName: 'Indonesia',
    ref: null,
    precedence: null,
    alias: [
      'Batu',
      'Kota Batu',
      'ML',
      'Bromo',
      'Ngalam',
      'AbdulrahmanSaleh',
      'Abdul Rahman Saleh',
      'Abdulrahman Saleh',
      'Abdul Rachmansaleh',
      'Abdul Rachman Saleh'
    ]
  },
  {
    value: 'SUB',
    label: 'Juanda (SUB) - Surabaya',
    airportName: 'Juanda',
    cityName: 'Surabaya',
    id: '5b77a1b0e7941b3b942e7a87',
    airportLocation: 'Surabaya, Indonesia',
    type: 'airport',
    cityCode: 'SUBC',
    countryName: 'Indonesia',
    ref: null,
    precedence: null,
    alias: [
      'Suroboyo',
      'Sidoarjo',
      'Juanda ',
      'Yuanda ',
      ' Surabaya',
      'Sura Baya ',
      ' Suro Boyo ',
      ' SBY',
      'Sur',
      'SUB'
    ]
  },
  {
    value: 'KNO',
    label: 'Kuala Namu (KNO) - Medan',
    airportName: 'Kuala Namu',
    cityName: 'Medan',
    id: '5b77a1aee7941b3b942e5e16',
    airportLocation: 'Medan, Indonesia',
    type: 'airport',
    cityCode: 'MESC',
    countryName: 'Indonesia',
    ref: null,
    precedence: null,
    alias: [
      'Kualanamu',
      'Deli Serdang',
      'Deliserdang',
      'MDN',
      'Sumatra Utara',
      'Sumut',
      'Danau',
      'Toba',
      'KNO'
    ]
  },
  {
    value: 'CGK',
    label: 'Soekarno Hatta (CGK) - Jakarta',
    airportName: 'Soekarno Hatta',
    cityName: 'Jakarta',
    id: '5b77a1ade7941b3b942e4c1d',
    airportLocation: 'Jakarta, Indonesia',
    type: 'airport',
    cityCode: 'JKTC',
    countryName: 'Indonesia',
    ref: 'JKTC',
    precedence: null,
    alias: [
      'Soekarno-Hatta',
      'SoekarnoHatta',
      'Soekarno Hatta',
      'Soetta',
      'Jakarta',
      'JKT',
      'DKI Jakarta',
      'Tangerang',
      'Cengkareng'
    ]
  },
  {
    value: 'UPG',
    label: 'Sultan Hasanuddin (UPG) - Makassar',
    airportName: 'Sultan Hasanuddin',
    cityName: 'Makassar',
    id: '5b77a1b0e7941b3b942e7d87',
    airportLocation: 'Makassar, Indonesia',
    type: 'airport',
    cityCode: 'UPGC',
    countryName: 'Indonesia',
    ref: null,
    precedence: null,
    alias: [
      'Ujung Pandang',
      'Ujungpandang',
      'Makasar',
      'Sultan Hasanuddin',
      'Hasanuddin ',
      ' Makassar ',
      ' Terbang Kadieng ',
      'Kadieng'
    ]
  },
  {
    value: 'YIA',
    label: 'Yogyakarta Kulon Progo (YIA) - Yogyakarta',
    airportName: 'Yogyakarta Kulon Progo',
    cityName: 'Yogyakarta',
    id: '5ccba38de7941b6fa83e9555',
    airportLocation: 'Yogyakarta, Indonesia',
    type: 'airport',
    cityCode: 'JOGC',
    countryName: 'Indonesia',
    ref: 'JOGC',
    precedence: null,
    alias: [
      'kulonprogo',
      'yogya',
      'jogja',
      'yogyakarta',
      'jogjakarta',
      'yk',
      'Borobudur',
      'Prambanan'
    ]
  },
  {
    value: 'DPS',
    label: 'Ngurah Rai (DPS) - Denpasar-Bali',
    airportName: 'Ngurah Rai',
    cityName: 'Denpasar-Bali',
    id: '5b77a1ade7941b3b942e4e7b',
    airportLocation: 'Denpasar-Bali, Indonesia',
    type: 'airport',
    cityCode: 'DPSC',
    countryName: 'Indonesia',
    ref: null,
    precedence: null,
    alias: ['Ngurahrai', 'I Gusti Ngurah Rai', 'Gusti Ngurah Rai', 'I Gusti', 'Bali', 'Bal', 'DPS']
  },
  {
    value: 'BDJ',
    label: 'Syamsuddin Noor (BDJ) - Banjarmasin',
    airportName: 'Syamsuddin Noor',
    cityName: 'Banjarmasin',
    id: '5b77a1ace7941b3b942e458f',
    airportLocation: 'Banjarmasin, Indonesia',
    type: 'airport',
    cityCode: 'BDJC',
    countryName: 'Indonesia',
    ref: null,
    precedence: null,
    alias: [
      'Banjarbaru',
      'Banjar masin ',
      'Banjar baru',
      'Samsudin',
      'Nur',
      'Syamsudinnoor',
      'Samsudin Nur',
      'samsudinnur',
      'Syamsudin Nur',
      'Samsudin Noor',
      'Kalsel',
      'Kalimantan',
      'Selatan'
    ]
  },
  {
    value: 'LOP',
    label: 'Lombok (LOP) - Praya',
    airportName: 'Lombok',
    cityName: 'Praya',
    id: '5b77a1afe7941b3b942e63ec',
    airportLocation: 'Praya, Indonesia',
    type: 'airport',
    cityCode: 'LOPC',
    countryName: 'Indonesia',
    ref: null,
    precedence: null,
    alias: [
      'Lombok',
      'Nusa Tenggara Barat',
      'NTB',
      'Mataram',
      'Zainuddin Abdul Madjid',
      'Zainuddin Abdul Majid',
      'Zainudin Abdul Majid',
      'Abdul Madjid',
      'Abdul Majid',
      'Selaparang',
      'Mataram',
      'Mandalika'
    ]
  },
  {
    value: 'SRG',
    label: 'Achmad Yani (SRG) - Semarang',
    airportName: 'Achmad Yani',
    cityName: 'Semarang',
    id: '5b77a1b0e7941b3b942e7a43',
    airportLocation: 'Semarang, Indonesia',
    type: 'airport',
    cityCode: 'SRGC',
    countryName: 'Indonesia',
    ref: null,
    precedence: null,
    alias: [
      'Ahmad Yani ',
      'Ahmadyani ',
      'Achmad Yani',
      'Achmadyani ',
      ' Lawang Sewu ',
      ' Simpanglima',
      'Simpang lima',
      ' Semarang ',
      ' SMG'
    ]
  }
];

export const defaultAirportSelected = {
  arrival: {
    value: 'SUB',
    label: 'Juanda (SUB) - Surabaya',
    airportName: 'Juanda',
    cityName: 'Surabaya',
    id: '5b77a1b0e7941b3b942e7a87',
    airportLocation: 'Surabaya, Indonesia',
    type: 'airport',
    cityCode: 'SUBC',
    countryName: 'Indonesia',
    ref: null,
    precedence: null,
    alias: [
      'Suroboyo',
      'Sidoarjo',
      'Juanda ',
      'Yuanda ',
      ' Surabaya',
      'Sura Baya ',
      ' Suro Boyo ',
      ' SBY',
      'Sur',
      'SUB'
    ]
  },
  departure: {
    value: 'CGK',
    label: 'Soekarno Hatta (CGK) - Jakarta',
    airportName: 'Soekarno Hatta',
    cityName: 'Jakarta',
    id: '5b77a1ade7941b3b942e4c1d',
    airportLocation: 'Jakarta, Indonesia',
    type: 'airport',
    cityCode: 'JKTC',
    countryName: 'Indonesia',
    ref: 'JKTC',
    precedence: null,
    alias: [
      'Soekarno-Hatta',
      'SoekarnoHatta',
      'Soekarno Hatta',
      'Soetta',
      'Jakarta',
      'JKT',
      'DKI Jakarta',
      'Tangerang',
      'Cengkareng'
    ]
  }
};
